### ISSUE TITLE
App is crashing on opening OTPScreen

### ISSUE THREAD

**Issue by scorchy38** [HathTech/flutter-firebase-tutorials#3]
`*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff23c4f02e __exceptionPreprocess + 350
	1   libobjc.A.dylib                     0x00007fff50b97b20 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff23c4ee6c +[NSException raise:format:] + 188
	3   Runner                              0x0000000104f05ce1 -[FIRPhoneAuthProvider verifyPhoneNumber:UIDelegate:completion:] + 193
	4   Runner                              0x0000000104ffe83d -[FLTFirebaseAuthPlugin handleMethodCall:result:] + 18109
	5   Flutter                             0x0000000105329b35 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 104
	6   Flutter                             0x00000001052bd920 _ZNK7flutter21PlatformMessageRouter21HandlePlat<…>
Lost connection to device.
`

with this message, kindly help asap, i have used your code as it is in my project, no changes.

**Comment by HathTech** [comment]
Change com.googlesecure...
From Google_Services.plist in Info.plist

Thanks and Regards,
Raja Babu
Team Hathtech

**Comment by scorchy38** [comment]
Thanks, I got it solved by adding the required keys in my info.plist file along with the reserved client id.
